Dir {
    ArchiveDir "docs";
    CacheDir "cache";
};

Default {
    Packages::Compress ". gzip";
};

Tree "dists/stable" {
    Sections "main";
    Architectures "all aarch64 arm i686 x86_64";
};
TreeDefault {
    Directory "pool";
    Packages "$(DIST)/$(SECTION)/binary-$(ARCH)/Packages";
    BinCacheDB "packages-$(ARCH).db";
};

APT::FTPArchive::Release {
    Origin "Siak Hooi";
    Label "Siak Hooi's APT Repository for Termux";
    Suite "stable";
    Codename "stable";
    Components "main";
    Architectures "aarch64 arm i686 x86_64 all";
};

